apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-php-ingress
  annotations:
    kubernetes.io/ingress.class: alb # or "nginx"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devops-php-svc
                port:
                  number: 80
